const Booklist = [
    {
      "author": "Chinua Achebe",
      "country": "Nigeria",
      "imageLink": "./images/things-fall-apart.jpeg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Things_Fall_Apart",
      "pages": 209,
      "title": "Things Fall Apart",
      "year": 1958,
      "number":18,
    },
    {
      "author": "Hans Christian Andersen",
      "country": "Denmark",
      "imageLink": "images/fairytails.jpg",
      "language": "Danish",
      "link": "https://en.wikipedia.org/wiki/Hans_Christian_Andersen",
      "pages": 784,
      "title": "Fairy Tales",
      "year": 1836,
      "number":10,
    },
    {
      "author": "Dante Alighieri",
      "country": "Italy",
      "imageLink": "images/thedivinecomedy.jpg",
      "language": "Italian",
      "link": "https://en.wikipedia.org/wiki/Divine_Comedy",
      "pages": 928,
      "title": "The Divine Comedy",
      "year": 1320,
      "number":8,
    },
    {
      "author": "Jane Austen",
      "country": "United Kingdom",
      "imageLink": "images/PrideAndPrejudice.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice",
      "pages": 279,
      "title": "Pride and Prejudice",
      "year": 1813,
      "number":10,
    },
    {
      "author": "Honoré de Balzac",
      "country": "France",
      "imageLink": "images/leperegoriot.png",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot",
      "pages": 443,
      "title": "Le Père Goriot",
      "year": 1835,
      "number":9,
    },
    {
      "author": "Samuel Beckett",
      "country": "Republic of Ireland",
      "imageLink": "images/Molloy.jpg",
      "language": "French, English",
      "link": "https://en.wikipedia.org/wiki/Molloy_(novel)",
      "pages": 256,
      "title": "Molloy",
      "year": 1951,
      "number":11,
    },
    {
      "author": "Jorge Luis Borges",
      "country": "Argentina",
      "imageLink": "images/Ficciones.jpg",
      "language": "Spanish",
      "link": "https://en.wikipedia.org/wiki/Ficciones",
      "pages": 224,
      "title": "Ficciones",
      "year": 1944,
      "number":8,
    },
    {
      "author": "Emily Brontë",
      "country": "United Kingdom",
      "imageLink": "images/wuthering-heights.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Wuthering_Heights",
      "pages": 342,
      "title": "Wuthering Heights",
      "year": 1847,
      "number":5,
    },
    {
      "author": "Albert Camus",
      "country": "France",
      "imageLink": "images/strangernovel.jpeg",
      "language": "French",
      "link": "https://www.google.com/books/edition/The_Stranger/7qylv1KYf0kC?hl=en&gbpv=1&printsec=frontcover",
      "pages": 185,
      "title": "The Stranger",
      "year": 1942,
      "number":8,
    },
    {
      "author": "Louis-Ferdinand Céline",
      "country": "France",
      "imageLink": "images/journey.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night",
      "pages": 505,
      "title": "Journey to the End of the Night",
      "year": 1932,
      "number":0,
    }
  ]

  export default Booklist;
  